"""Added Track table

Revision ID: f233df0d07f8
Revises: 
Create Date: 2025-01-04 10:06:30.053969

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f233df0d07f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('updated', sa.Date(), nullable=False),
        sa.Column('current_count', sa.Integer(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_year'), 'track', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_year'), table_name='track')
    op.drop_table('track')
    # ### end Alembic commands ###
